// Shared popup style definitions

export const draftSavePopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
  modal: {
    backgroundColor: "#fff",
    padding: "24px 30px 32px",
    borderRadius: "10px",
    width: "420px",
    textAlign: "center",
    boxShadow: "0 10px 30px rgba(0,0,0,0.25)",
  },
  image: {
    width: "320px",
    height: "320px",
    marginTop: "-70px",
    marginBottom: "-140px",
    marginLeft: "23px",
    objectFit: "contain",
  },
  title: {
    fontSize: "22px",
    fontWeight: "700",
    marginBottom: "6px",
  },
  message: {
    fontSize: "14px",
    color: "#555",
    marginBottom: "24px",
  },
  button: {
    padding: "20px 30px",
    backgroundColor: "#0B3A6E",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
  },
};

export const successPopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
  modal: {
    backgroundColor: "#fff",
    padding: "24px 30px 32px",
    borderRadius: "10px",
    width: "420px",
    textAlign: "center",
    boxShadow: "0 10px 30px rgba(0,0,0,0.25)",
  },
  image: {
    width: "320px",
    height: "320px",
    marginTop: "-70px",
    marginBottom: "-140px",
    marginLeft: "23px",
    objectFit: "contain",
  },
  title: {
    fontSize: "22px",
    fontWeight: "700",
    marginBottom: "6px",
  },
  message: {
    fontSize: "14px",
    color: "#555",
    marginBottom: "24px",
  },
  button: {
    padding: "10px 30px",
    backgroundColor: "#0B3A6E",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
  },
};

export const editOptionsPopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "20px",
    padding: "0",
    width: "500px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.3)",
    border: "2px solid #000",
  },
  header: {
    backgroundColor: "#0B3A6E",
    color: "white",
    padding: "20px",
    fontSize: "24px",
    fontWeight: "700",
    textAlign: "center",
    borderRadius: "18px 18px 0 0",
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "transparent",
    border: "none",
    color: "white",
    fontSize: "24px",
    fontWeight: "700",
    cursor: "pointer",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "background-color 0.2s",
    lineHeight: "1",
    padding: 0,
  },
  subHeader: {
    fontSize: "20px",
    fontWeight: "700",
    textAlign: "center",
    margin: "30px 0 20px",
    color: "#000",
  },
  optionRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "15px 40px",
    margin: "15px 30px",
    border: "2px solid #000",
    borderRadius: "8px",
    backgroundColor: "#fff",
  },
  optionLabel: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#000",
  },
  toggleGroup: {
    display: "flex",
    gap: "15px",
  },
  toggleButton: {
    padding: "8px 20px",
    fontSize: "14px",
    fontWeight: "600",
    border: "none",
    borderRadius: "20px",
    cursor: "pointer",
    minWidth: "60px",
    transition: "all 0.2s",
  },
  activeYes: {
    backgroundColor: "#4CAF50",
    color: "white",
  },
  activeNo: {
    backgroundColor: "#f44336",
    color: "white",
  },
  inactiveButton: {
    backgroundColor: "#9e9e9e",
    color: "white",
  },
  proceedButton: {
    backgroundColor: "#0B3A6E",
    color: "white",
    padding: "12px 40px",
    fontSize: "16px",
    fontWeight: "600",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    display: "block",
    margin: "30px auto 30px",
    boxShadow: "0 4px 10px rgba(11, 58, 110, 0.3)",
  },
};

export const multipleRakeSerialPopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    overflow: "hidden",
    width: "450px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.3)",
  },
  header: {
    backgroundColor: "#0B3A6E",
    color: "white",
    padding: "20px",
    fontSize: "18px",
    fontWeight: "700",
    textAlign: "center",
    borderRadius: "12px 12px 0 0",
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "transparent",
    border: "none",
    color: "white",
    fontSize: "24px",
    fontWeight: "700",
    cursor: "pointer",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "background-color 0.2s",
    lineHeight: "1",
    padding: 0,
  },
  body: {
    padding: "30px 20px",
    textAlign: "center",
  },
  question: {
    fontSize: "16px",
    fontWeight: "700",
    color: "#000",
    marginBottom: "30px",
    margin: "0 0 30px 0",
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
  },
  button: {
    padding: "12px 40px",
    backgroundColor: "#808080",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
};

export const warningPopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    overflow: "hidden",
    width: "450px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.3)",
  },
  header: {
    backgroundColor: "#0B3A6E",
    color: "white",
    padding: "20px",
    fontSize: "18px",
    fontWeight: "700",
    textAlign: "center",
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "transparent",
    border: "none",
    color: "white",
    fontSize: "24px",
    fontWeight: "700",
    cursor: "pointer",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    transition: "background-color 0.2s",
    lineHeight: "1",
    padding: 0,
  },
  body: {
    padding: "30px 20px",
    textAlign: "center",
  },
  icon: {
    width: "80px",
    height: "80px",
    margin: "0 auto 20px",
    objectFit: "contain",
    display: "block",
  },
  message: {
    fontSize: "16px",
    fontWeight: "500",
    color: "#333",
    marginBottom: "25px",
    lineHeight: "1.5",
    whiteSpace: "pre-line",
  },
  button: {
    padding: "12px 40px",
    backgroundColor: "#0B3A6E",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    transition: "background-color 0.2s",
  },
};

export const cancelPopupStyles = {
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    overflow: "hidden",
    width: "500px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.3)",
  },
  header: {
    backgroundColor: "#0B3A6E",
    color: "white",
    padding: "20px",
    fontSize: "18px",
    fontWeight: "700",
    textAlign: "center",
  },
  body: {
    padding: "30px 20px",
  },
  question: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#000",
    marginBottom: "15px",
  },
  textarea: {
    width: "100%",
    padding: "10px",
    fontSize: "14px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    marginBottom: "20px",
    fontFamily: "inherit",
    resize: "vertical",
  },
  buttonGroup: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
  },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  confirmButton: {
    padding: "10px 20px",
    backgroundColor: "#dc3545",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
};
